drivers/net: fix indication of allocation
When experimenting with the -std=c2x compiler option the error below
popped up:

../drivers/net/bnxt/tf_core/tf_sram_mgr.c:952:39: error: incompatible
   types when assigning to type ‘_Bool *’ from type ‘_Bool’

The code indicates that the intention was to assign false to the bool
being pointed to, not to the pointer itself.

Fixes: 37ff91c158a3 ("net/bnxt: add SRAM manager model")
Cc: stable@dpdk.org

Signed-off-by: Andre Muezerie <andremue@linux.microsoft.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>