hash: fix GFNI implementation build with GCC 12
On a system that has AVX512F and GFNI, compiling fails with:

In file included from /usr/lib/gcc/x86_64-redhat-linux/12/include/immintrin.h:71,
                 from /usr/lib/gcc/x86_64-redhat-linux/12/include/x86intrin.h:32,
                 from ../../../git/pub/dpdk.org/main/lib/eal/x86/include/rte_vect.h:31,
                 from ../../../git/pub/dpdk.org/main/lib/eal/x86/include/rte_memcpy.h:17,
                 from ../../../git/pub/dpdk.org/main/lib/mempool/rte_mempool.h:48,
                 from ../../../git/pub/dpdk.org/main/lib/mbuf/rte_mbuf.h:38,
                 from ../../../git/pub/dpdk.org/main/lib/net/rte_ip.h:33,
                 from ../../../git/pub/dpdk.org/main/lib/hash/rte_thash.h:25,
                 from ../../../git/pub/dpdk.org/main/lib/hash/rte_thash.c:7:
In function ‘_mm512_mask_permutexvar_epi8’,
    inlined from ‘__rte_thash_gfni’ at
	../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:142:17,
    inlined from ‘rte_thash_gfni’ at
	../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:182:20,
    inlined from ‘rte_thash_adjust_tuple’ at
	../../../git/pub/dpdk.org/main/lib/hash/rte_thash.c:784:11:
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512vbmiintrin.h:97:20:
	error: ‘tuple_bytes’ may be used uninitialized [-Werror=maybe-uninitialized]
   97 |   return (__m512i) __builtin_ia32_permvarqi512_mask ((__v64qi) __B,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   98 |                                                      (__v64qi) __A,
      |                                                      ~~~~~~~~~~~~~~
   99 |                                                      (__v64qi) __W,
      |                                                      ~~~~~~~~~~~~~~
  100 |                                                      (__mmask64) __M);
      |                                                      ~~~~~~~~~~~~~~~~

And:

In file included from ../../../git/pub/dpdk.org/main/lib/hash/rte_thash_gfni.h:17,
                 from ../../../git/pub/dpdk.org/main/lib/hash/rte_thash.h:27:
../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:
	In function ‘rte_thash_adjust_tuple’:
../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:91:33:
	note: ‘tuple_bytes’ was declared here
   91 |         __m512i vals, matrixes, tuple_bytes, tuple_bytes_2;
      |                                 ^~~~~~~~~~~
In function ‘_mm512_mask_permutexvar_epi8’,
    inlined from ‘__rte_thash_gfni’ at
	../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:142:17,
    inlined from ‘rte_thash_gfni’ at
	../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:182:20,
    inlined from ‘rte_thash_adjust_tuple’ at
	../../../git/pub/dpdk.org/main/lib/hash/rte_thash.c:784:11:
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512vbmiintrin.h:97:20:
	error: ‘permute_mask’ may be used uninitialized [-Werror=maybe-uninitialized]
   97 |   return (__m512i) __builtin_ia32_permvarqi512_mask ((__v64qi) __B,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   98 |                                                      (__v64qi) __A,
      |                                                      ~~~~~~~~~~~~~~
   99 |                                                      (__v64qi) __W,
      |                                                      ~~~~~~~~~~~~~~
  100 |                                                      (__mmask64) __M);
      |                                                      ~~~~~~~~~~~~~~~~
../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:
	In function ‘rte_thash_adjust_tuple’:
../../../git/pub/dpdk.org/main/lib/hash/rte_thash_x86_gfni.h:92:30:
	note: ‘permute_mask’ was declared here
   92 |         __mmask64 load_mask, permute_mask, permute_mask_2;
      |                              ^~~~~~~~~~~~
cc1: all warnings being treated as errors

Set those variables to 0.

Fixes: 4fd8c4cb0de1 ("hash: add new Toeplitz hash implementation")
Cc: stable@dpdk.org

Signed-off-by: David Marchand <david.marchand@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>