buildtools: remove invalid option for Microsoft linker
When compiling "drivers" directory with MSVC the errors below popped up:

drivers/rte_mempool_stack.pmd.c(1): error C2143: syntax error:
    missing ')' before '('
drivers/rte_mempool_stack.pmd.c(1): error C2059: syntax error: ')'
drivers/rte_mempool_stack.pmd.c(1): error C2059: syntax error: ')'
drivers/rte_mempool_stack.pmd.c(1): error C2143: syntax error:
    missing ')' before 'const'
drivers/rte_mempool_stack.pmd.c(1): error C2091: function returns function

The fix is to use common macros compatible with MSVC.

Signed-off-by: Andre Muezerie <andremue@linux.microsoft.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>