app/test-eventdev: fix issues with clang 21.1.4
Fix the following error seen with clang 21.1.4

app/test-eventdev/test_perf_common.c:1340:30: error: variable
'event' is uninitialized when passed as a const pointer argument
here [-Werror,-Wuninitialized-const-pointer]

Fixes: b25a66c49e8d ("app/eventdev: add DMA adapter performance test")
Cc: stable@dpdk.org

Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>