eventdev: fix build with clang 21
Fix 16-bits formatting issues reported by clang 21 on Fedora 43:

../lib/eventdev/rte_event_crypto_adapter.c:1461:4: error:
	format specifies type 'unsigned char' but the argument has type
	'uint16_t' (aka 'unsigned short') [-Werror,-Wformat]
 1459 |     RTE_EDEV_LOG_ERR("Failed to get adapter caps dev %" PRIu8
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1460 |             " cdev %" PRIu8, adapter->eventdev_id,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1461 |             adapter->next_cdev_id);
      |             ^~~~~~~~~~~~~~~~~~~~~~

../lib/eventdev/rte_event_crypto_adapter.c:1592:46: error:
	format specifies type 'unsigned char' but the argument has type
	'uint16_t' (aka 'unsigned short') [-Werror,-Wformat]
 1592 |     RTE_EDEV_LOG_ERR("Invalid dev_id=%" PRIu8, cdev_id);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~

../lib/eventdev/rte_event_crypto_adapter.c:1613:45: error:
	format specifies type 'unsigned char' but the argument has type
	'uint16_t' (aka 'unsigned short') [-Werror,-Wformat]
 1612 |     RTE_EDEV_LOG_ERR("Event vectorization is not supported,"
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1613 |                      "dev %" PRIu8 " cdev %" PRIu8, dev_id, cdev_id);
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~

Fixes: c1749bc5ee10 ("eventdev: introduce event cryptodev vector type")
Fixes: 04ed18cd41f1 ("eventdev/crypto: support runtime set/get parameters")
Cc: stable@dpdk.org

Signed-off-by: David Marchand <david.marchand@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>