node: fix C++ compatibility errors (option 1)
C++ does not allow zero-sized unions - they end up being of size 1-byte,
which leads to C/C++ compatibility issues, flagged by the compiler.

  lib/node/rte_node_mbuf_dynfield.h:78:2: error: union has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]
   78 |         union {
	         |         ^
		 1 error generated.

Fix the error by defaulting to a having a 1-byte sized union rather than
zero-sized.

Fixes: 746e8736da70 ("node: add global mbuf dynfield")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>