app/mldev: fix build with debug
Compiling with -O0 and -g triggers these warnings:

../app/test-mldev/test_inference_common.c: In function
	‘ml_request_finish’:
../app/test-mldev/test_inference_common.c:946:51:
	error: ‘.q.’ directive output may be truncated writing 3 bytes
	into a region of size between 0 and 4095
	[-Werror=format-truncation=]
  946 |                 snprintf(str, sizeof(str) - 1, "%s.q.%d",
      |                                                   ^~~
	t->cmn.opt->filelist[req->fid].output, obj_idx);
../app/test-mldev/test_inference_common.c:946:48: note: using the range
	[-2147483648, 2147483647] for directive argument
  946 |                 snprintf(str, sizeof(str) - 1, "%s.q.%d",
      |                                                ^~~~~~~~~
	t->cmn.opt->filelist[req->fid].output, obj_idx);
../app/test-mldev/test_inference_common.c:946:17: note: ‘snprintf’
	output between 5 and 4110 bytes into a destination of size 4095
  946 |                 snprintf(str, sizeof(str) - 1, "%s.q.%d",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	t->cmn.opt->filelist[req->fid].output, obj_idx);
../app/test-mldev/test_inference_common.c:952:51: error: ‘.’ directive
	output may be truncated writing 1 byte into a region of size
	between 0 and 4095 [-Werror=format-truncation=]
  952 |                 snprintf(str, sizeof(str) - 1, "%s.%d",
      |                                                   ^
	t->cmn.opt->filelist[req->fid].output, obj_idx);
../app/test-mldev/test_inference_common.c:952:48: note: using the range
	[-2147483648, 2147483647] for directive argument
  952 |                 snprintf(str, sizeof(str) - 1, "%s.%d",
      |                                                ^~~~~~~
	t->cmn.opt->filelist[req->fid].output, obj_idx);
../app/test-mldev/test_inference_common.c:952:17: note: ‘snprintf’
	output between 3 and 4108 bytes into a destination of size 4095
  952 |                 snprintf(str, sizeof(str) - 1, "%s.%d",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	t->cmn.opt->filelist[req->fid].output, obj_idx);
../app/test-mldev/test_inference_common.c:929:51: error: ‘.q’ directive
	output may be truncated writing 2 bytes into a region of size
	between 0 and 4095 [-Werror=format-truncation=]
  929 |                 snprintf(str, sizeof(str) - 1, "%s.q",
      |                                                   ^~
	t->cmn.opt->filelist[req->fid].output);
../app/test-mldev/test_inference_common.c:929:17: note: ‘snprintf’
	output between 3 and 4098 bytes into a destination of size 4095
  929 |                 snprintf(str, sizeof(str) - 1, "%s.q",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	t->cmn.opt->filelist[req->fid].output);
../app/test-mldev/test_inference_common.c:935:51: error: ‘snprintf’
	output may be truncated before the last format character
	[-Werror=format-truncation=]
  935 |                 snprintf(str, sizeof(str) - 1, "%s",
      |                                                   ^
	t->cmn.opt->filelist[req->fid].output);
../app/test-mldev/test_inference_common.c:935:17: note: ‘snprintf’
	output between 1 and 4096 bytes into a destination of size 4095
  935 |                 snprintf(str, sizeof(str) - 1, "%s",
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	t->cmn.opt->filelist[req->fid].output);

Fix unsigned integer format, and switch to dynamic allocations.

Fixes: da6793390596 ("app/mldev: support inference validation")

Signed-off-by: David Marchand <david.marchand@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>