eal: fix missing include
This patch adds the missing include and fixes the build error:
/dpdk/build/include/rte_uuid.h: In function 'rte_uuid_copy':
/dpdk/build/include/rte_uuid.h:58:2: error: implicit declaration
of function 'memcpy' [-Werror=implicit-function-declaration]
  memcpy(dst, src, sizeof(rte_uuid_t));
  ^~~~~~

Fixes: 6bc67c497a51 ("eal: add uuid API")
Cc: stable@dpdk.org

Signed-off-by: Yunjian Wang <yunjian.wang@foxmail.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>