vhost: compilation fix for GCC-12
../lib/vhost/virtio_net.c:941:35: error:
		'buf_vec[0].buf_len' may be used uninitialized
		[-Werror=maybe-uninitialized]
  941 |         buf_len = buf_vec[vec_idx].buf_len;
      |                   ~~~~~~~~~~~~~~~~^~~~~~~~
../lib/vhost/virtio_net.c: In function 'virtio_dev_rx_packed':
../lib/vhost/virtio_net.c:1285:27: note: 'buf_vec' declared here
 1285 |         struct buf_vector buf_vec[BUF_VECTOR_MAX];
      |                           ^~~~~~~
cc1: all warnings being treated as errors

Fixes: 93520085efda ("vhost: add packed ring single enqueue")
Cc: stable@dpdk.org

Signed-off-by: Amit Prakash Shukla <amitprakashs@marvell.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>