buildtools/cmdline: fix meson error when used as a subproject
Fix the following error when using dpdk as a subproject:

 subprojects/dpdk/buildtools/subproject/meson.build:28:56:
 ERROR: Unknown function "file".

This was obviously never tested in its submitted form.

Cc: stable@dpdk.org
Fixes: 7d8c608faa7f ("buildtools/cmdline: allow using script in subproject")

Signed-off-by: Robin Jarry <rjarry@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>