net/mlx5: fix build failure on Windows
__always_inline is not supported on Windows, let's use
__rte_always_inline instead.

..\drivers\net\mlx5/mlx5_hws_cnt.h:162:8: error: unknown type name '__always_inline'

static __always_inline struct mlx5_hws_cnt_pool *

       ^

..\drivers\net\mlx5/mlx5_hws_cnt.h:165:9: error: incompatible pointer types returning 'struct mlx5_hws_cnt_pool *' from a function with result type 'int *' [-Werror,-Wincompatible-pointer-types]

        return cpool->cfg.host_cpool ? cpool->cfg.host_cpool : cpool;

Fixes: 13ea6bdcc7ee ("net/mlx5: support counters in cross port shared mode")

Signed-off-by: Maxime Coquelin <maxime.coquelin@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>