ethdev: fix strict aliasing lead to link cannot be up
Fix a problem introduced by a compiler upgrade (from gcc10 to gcc12.3),
which will lead the hns3 NIC can't link up. The root cause is strict
aliasing violation in rte_eth_linkstatus_set() with hns3 driver, see
[1] for more details.

This commit use union to avoid such aliasing violation.

Note: DPDK CI report compiler error (see [2] for more details):
../drivers/net/cxgbe/cxgbe_ethdev.c:214:9: error: missing braces around
initializer [-Werror=missing-braces]
  struct rte_eth_link new_link = { 0 };
So this commit replace { 0 } with memset in cxgbe.

[1] Strict aliasing problem with rte_eth_linkstatus_set()
    https://marc.info/?l=dpdk-dev&m=171274148514777&w=3
[2] https://mails.dpdk.org/archives/test-report/2024-April/637966.html

Cc: stable@dpdk.org

Signed-off-by: Chengwen Feng <fengchengwen@huawei.com>
Signed-off-by: Dengdui Huang <huangdengdui@huawei.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>