crypto/zuc: fix gcc11 maybe-uninitialized warnings
gcc11 complains that some arrays may be uninitialized in
process_zuc_hash_op(). This is because their initialization
depends on num_ops being > 0.

For example:
$ gcc --version
gcc (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1)

In file included from ../drivers/crypto/zuc/zuc_pmd_private.h:8,
                 from ../drivers/crypto/zuc/rte_zuc_pmd.c:13:
../drivers/crypto/zuc/rte_zuc_pmd.c: In function ‘process_zuc_hash_op’:
../drivers/crypto/zuc/rte_zuc_pmd.c:279:33: error: ‘hash_keys’ may be used uninitialized [-Werror=maybe-uninitialized]
  279 |         IMB_ZUC_EIA3_N_BUFFER(qp->mb_mgr, (const void **)hash_keys,
      |                                 ^
../drivers/crypto/zuc/rte_zuc_pmd.c:279:33: note: by argument 1 of type ‘const void * const*’ to ‘void(const void * const*, const void * const*, const void * const*, const uint32_t *, uint32_t **, const uint32_t)’ {aka ‘void(const void * const*, const void * const*, const void * const*, const unsigned int *, unsigned int **, const unsigned int)’}
../drivers/crypto/zuc/rte_zuc_pmd.c:245:21: note: ‘hash_keys’ declared here
  245 |         const void *hash_keys[ZUC_MAX_BURST];
      |                     ^~~~~~~~~

This function is only called with num_ops > 0 because of
checks in process_zuc_hash_op().

To remove the warning initialize the arrays.

Signed-off-by: Kevin Traynor <ktraynor@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>