app/testpmd: fix uint build error with musl libc
Improve portability by avoid use non-standard 'uint'.

Use uint8_t for hash_key_len as rss_key_len is a uint8_t type.

This solves following build error when building with musl libc:

In file included from ../app/test-pmd/cmdline.c:74:
../app/test-pmd/testpmd.h:813:29: error: unknown type name 'uint'; did
you mean 'int'?
  813 |          uint8_t *hash_key, uint hash_key_len);
      |                             ^~~~
      |                             int

Fixes: 8205e241b2b0 ("app/testpmd: add missing type to RSS hash commands")
Cc: stable@dpdk.org

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>
Signed-off-by: 0-day Robot <robot@bytheb.org>