net/mlx5: fix build with clang 14
clang 14 raises the following warning:

../drivers/net/mlx5/linux/mlx5_ethdev_os.c:1137:52: error: 'fscanf'
    may overflow; destination buffer in argument 3 has size 16, but the
    corresponding specifier may require size 17
    [-Werror,-Wfortify-source]
                ret = fscanf(file, "%" RTE_STR(IF_NAMESIZE) "s",
                    port_name);

Extend port_name so that it can fit a null terminated string.

Fixes: 63d1db710fbc ("net/mlx5: fix unlimited parsing of switch info")
Fixes: 1256805dd54d ("net/mlx5: move Linux-specific functions")
Cc: stable@dpdk.org

Signed-off-by: David Marchand <david.marchand@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>