eal/windows: add sys/queue.h.
When compiling OVS, lib/dpdk.c, found the missing header.
In file included from ../lib/dpdk.c:27:
C:\temp\dpdk\include\rte_log.h:24:10: fatal error: 'sys/queue.h' file
not found
^~~~~~~~~~~~~
1 warning and 1 error generated.

Signed-off-by: William Tu <u9012063@gmail.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>