net/mlx5: fix MAC address initialization
Offending patch added code which broke compilation on GCC 15,
where MAC address was initialized with a string, causing the following
errors:

../drivers/net/mlx5/mlx5_flow.c:
  In function ‘mlx5_legacy_dmac_flow_create’:
../drivers/net/mlx5/mlx5_flow.c:8568:44:
  error: initializer-string for array of ‘unsigned char’ is too long
    [-Werror=unterminated-string-initialization]
 8568 |                 .hdr.dst_addr.addr_bytes =
"\xff\xff\xff\xff\xff\xff",
      |
^~~~~~~~~~~~~~~~~~~~~~~~~~

../drivers/net/mlx5/mlx5_flow.c: In function
‘mlx5_legacy_dmac_vlan_flow_create’:
../drivers/net/mlx5/mlx5_flow.c:8583:44:
  error: initializer-string for array of ‘unsigned char’ is too long
    [-Werror=unterminated-string-initialization]
 8583 |                 .hdr.dst_addr.addr_bytes =
"\xff\xff\xff\xff\xff\xff",
      |
^~~~~~~~~~~~~~~~~~~~~~~~~~

This patch fixes this issue by converting it to array initialization.

Fixes: cf99567fe566 ("net/mlx5: add legacy unicast flow rules management")

Signed-off-by: Dariusz Sosnowski <dsosnowski@nvidia.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>