bus/fslmc: fix warning in device scan
With latest glibc (Fedora Rawhide):
../drivers/bus/fslmc/fslmc_bus.c: In function ‘rte_fslmc_parse’:
../drivers/bus/fslmc/fslmc_bus.c:298:15: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   298 |         t_ptr = strchr(sep, '.');
       |               ^
Fixes: e67a61614d0b ("bus/fslmc: support device iteration")

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
Acked-by: Hemant Agrawal <hemant.agrawal@nxp.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>