ring: compilation fix with GCC-12
GCC 12 raises the following warning:

In function '__rte_ring_dequeue_elems_128',
    inlined from '__rte_ring_dequeue_elems' at
		../lib/ring/rte_ring_elem_pvt.h:262:3,
    inlined from '__rte_ring_do_hts_dequeue_elem' at
		../lib/ring/rte_ring_hts_elem_pvt.h:237:3,
    inlined from 'rte_ring_mc_hts_dequeue_bulk_elem' at
		../lib/ring/rte_ring_hts.h:83:9,
    inlined from 'rte_ring_dequeue_bulk_elem' at
		../lib/ring/rte_ring_elem.h:391:10,
    inlined from 'rte_ring_dequeue_elem' at
		../lib/ring/rte_ring_elem.h:476:9,
    inlined from 'rte_ring_dequeue' at
		../lib/ring/rte_ring.h:463:9,
    inlined from 'rxa_intr_ring_dequeue' at
		../lib/eventdev/rte_event_eth_rx_adapter.c:1196:10:
../lib/ring/rte_ring_elem_pvt.h:234:25: error: 'memcpy' writing
	32 bytes into a region of size 8 overflows the destination
	[-Werror=stringop-overflow=]
  234 |    memcpy((void *)(obj + i), (void *)(ring + idx), 32);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Replacing memcpy with rte_memcpy fixes the GCC-12 compilation issue.
Also it would be better to change to rte_memcpy as the function is
called in fastpath.

Bugzilla ID: 1062
Fixes: 1fc73390bcf5 ("ring: refactor exported headers")
Cc: stable@dpdk.org

Signed-off-by: Amit Prakash Shukla <amitprakashs@marvell.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>