test/bbdev: use helper function to set IOVA addr
Use helper function rte_mbuf_iova_set to set IOVA address
to fix compilation failures.

Below error was observed:

dpdk/app/test-bbdev/test_bbdev_perf.c: In function ‘init_op_data_objs’:
dpdk/app/test-bbdev/test_bbdev_perf.c:1145:11: error:
‘struct rte_mbuf’ has no member named ‘buf_iova’
 1145 |     m_head->buf_iova = rte_malloc_virt2iova(data);
      |           ^~

Fixes: 0acdb98667 ("test/bbdev: add FFT operations cases")

Signed-off-by: Srikanth Yalavarthi <syalavarthi@marvell.com>
Change-Id: I9d4cda5f7fcd3a05b3cc8af7eaeccdf977b7fecd
Signed-off-by: 0-day Robot <robot@bytheb.org>