net/ice/base: fix build error for GCC 4.8.5
Code changes done for build issue as reported in Bug 817
error: dereferencing type-punned pointer will break strict-aliasing rules.
added union to avoid pointer dereferencing

Fixes: 39925373a333 ("net/ice/base: add parser execution main loop")
Cc: stable@dpdk.org

Signed-off-by: Aman Singh <aman.deep.singh@intel.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>