eal/windows: fix mingw build
When compiling with mingw on Ubuntu 23.10, I get the following compiler
error:

../../lib/eal/windows/eal_memory.c:77: error: "MEM_REPLACE_PLACEHOLDER" redefined [-Werror]
   77 | #define MEM_REPLACE_PLACEHOLDER   0x00004000
      |
In file included from /usr/share/mingw-w64/include/minwindef.h:163,
                 from /usr/share/mingw-w64/include/windef.h:9,
                 from /usr/share/mingw-w64/include/windows.h:69,
                 from ../../lib/eal/windows/include/rte_windows.h:32,
                 from ../../lib/eal/windows/include/rte_os_shim.h:9,
                 from ../../lib/eal/common/eal_internal_cfg.h:14,
                 from ../../lib/eal/windows/eal_memory.c:11:
/usr/share/mingw-w64/include/winnt.h:5710: note: this is the location of the previous definition
 5710 | #define MEM_REPLACE_PLACEHOLDER 0x4000

and a similar error for MEM_RESERVE_PLACEHOLDER. These errors can be
fixed by wrapping the two defines in #ifndef .. #endif blocks.

Fixes: 2a5d547a4a9b ("eal/windows: implement basic memory management")
Cc: dmitry.kozliuk@gmail.com
Cc: stable@dpdk.org

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>