kni: fix build with Linux 5.9
Build error seen with Linux kernel 5.9.

Build error:
kernel/linux/kni/kni_dev.h:104:30:
	error: passing argument 1 of ‘get_user_pages_remote’ from
	incompatible pointer type [-Werror=incompatible-pointer-types]
	ret = get_user_pages_remote(tsk, tsk->mm, iova, 1,

get_user_pages_remote() is changed in Linux kernel version 5.9 and
remove a parameter, struct task_struct *tsk:
Linux Commit 64019a2e467a ("mm/gup: remove task_struct pointer
for all gup code")

get_user_pages_remote() parameter updated with compile time Linux
kernel version check.

Cc: stable@dpdk.org

Signed-off-by: Min Hu (Connor) <humin29@huawei.com>
Reviewed-by: Wei Hu (Xavier) <xavier.huwei@huawei.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>