net/i40e: fix build with MinGW GCC 12
When compiling with MinGW GCC 12,
the rte_flow_item array is seen as read out of bound:

net/i40e/i40e_hash.c:389:47: error:
	array subscript 50 is above array bounds of ‘const uint64_t[50]’
	{aka ‘const long long unsigned int[50]’} [-Werror=array-bounds]
	389 | item_hdr = pattern_item_header[last_item_type];
	    |            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~

It seems the assert check done above this line has no impact.
A check is added to make the compiler happy.

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Signed-off-by: 0-day Robot <robot@bytheb.org>