kernel/freebsd: fix module build on FreeBSD 14
When building nic_uio module on FreeBSD 14, a build error is given in
the DRIVER_MODULE macro:

.../nic_uio.c:84:81: error: too many arguments provided to function-like macro invocation
DRIVER_MODULE(nic_uio, pci, nic_uio_driver, nic_uio_devclass, nic_uio_modevent, 0);
                                                                                ^
On FreeBSD 14, the devclass parameter is dropped from the macro, so we
conditionally compile a different invocation for BSD versions before/
after v14.

Bugzilla Id: 1335

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>