net/tap: fix compilation issues if HAVE_TCA_FLOWER is missing
If HAVE_TCA_FLOWER is undefined compilation errors / warnings may
appear. This addresses following spotted issues:

../drivers/net/tap/rte_eth_tap.c:2113:1: error: label ‘disable_rte_flow’
defined but not used [-Werror=unused-label]

../drivers/net/tap/rte_eth_tap.c:1908:26: error: unused parameter
‘remote_iface’ [-Werror=unused-parameter]

Fixes: bf7b7f437b49 ("net/tap: create netdevice during probing")
Cc: pascal.mazon@6wind.com

Signed-off-by: Tomasz Duszynski <tduszynski@marvell.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>