net/bnxt: fix compilation error on Redhat 8
.../drivers/net/bnxt/tf_ulp/ulp_def_rules.c: In function ‘bnxt_ulp_destroy_df_rules’:
  .../dpdk/drivers/net/bnxt/tf_ulp/ulp_def_rules.c:425:28: error:
    comparison is always true due to limited range of data type [-Werror=type-limits]
  for (port_id = 0; port_id < RTE_MAX_ETHPORTS; port_id++) {
                            ^

Fixes: 769de16872ab9 ('net/bnxt: fix port default rule create/destroy')
Cc: Ajit Khaparde <ajit.khaparde@broadcom.com>
Cc: Somnath Kotur <somnath.kotur@broadcom.com>

Signed-off-by: Thierry Herbelot <thierry.herbelot@6wind.com>
Acked-by: Somnath Kotur <somnath.kotur@broadcom.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>