cmdline-gen: fix error when command list has empty lines
Fix the following error when a command list file contains empty lines:

Traceback (most recent call last):
  File "buildtools/dpdk-cmdline-gen.py", line 202, in <module>
    main()
  File "buildtools/dpdk-cmdline-gen.py", line 184, in main
    process_commands(args.infile, sys.stdout, None, args.context_name)
  File "buildtools/dpdk-cmdline-gen.py", line 141, in process_commands
    cmd_inst, h_out, c_out = process_command(lineno, tokens.strip().spl…
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^…
  File "buildtools/dpdk-cmdline-gen.py", line 36, in process_command
    if tokens[0].startswith("<"):
       ~~~~~~^^^
IndexError: list index out of range

Use shlex.split() to properly split each line arguments into tokens and
strip comments.

If there are no tokens, ignore the line.

Fixes: 37666691e9ed ("buildtools: add a tool to generate cmdline boilerplate")

Cc: Bruce Richardson <bruce.richardson@intel.com>
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>