dmadev: fix build if RTE_DMADEV_DEBUG enabled
Missing definition of errnos causes build failure:

In file included from ../lib/dmadev/rte_dmadev_trace.h:16,
                 from ../lib/dmadev/rte_dmadev_trace_points.c:8:
../lib/dmadev/rte_dmadev.h: In function ‘rte_dma_copy’:
../lib/dmadev/rte_dmadev.h:1183:25: error: ‘EINVAL’ undeclared (first use in this function)
 1183 |                 return -EINVAL;
      |                         ^~~~~~

Bugzilla ID: 1814
Fixes: 8f1d23ece06a ("eal: deprecate RTE_FUNC_PTR_* macros")
Cc: david.marchand@redhat.com

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
Signed-off-by: 0-day Robot <robot@bytheb.org>